fix: indent of circle ci config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -40,13 +40,13 @@ commands:
     description: "Print debug info of npm auth"
     steps:
       - run:
-        name: "Verify npm token"
-        command: |
-          set -euo pipefail
-          echo "npm registry: $(npm config get registry)"
-          echo "npm userconfig: $(npm config get userconfig)"
-          test -f ~/.npmrc && echo "~/.npmrc exists" || (echo "~/.npmrc not found")
-          echo "npm user: $(npm whoami)"
+          name: "Verify npm token"
+          command: |
+            set -euo pipefail
+            echo "npm registry: $(npm config get registry)"
+            echo "npm userconfig: $(npm config get userconfig)"
+            test -f ~/.npmrc && echo "~/.npmrc exists" || (echo "~/.npmrc not found")
+            echo "npm user: $(npm whoami)"
 
   publish:
     description: "Publish packages to NPM registry if needed"
